version: "3"
services:
  frontend:
    restart: always
    build: ./frontend
    networks:
      ecsfs:
        aliases:
          - ecsfs.frontend
  backend:
    restart: always
    build: ./backend
    networks:
      ecsfs:
        aliases:
          - ecsfs.backend
  nginx:
    restart: always
    build: ./nginx
    networks:
      ecsfs:
        aliases:
          - ecsfs.nginx
    ports:
      - "80:80"

networks:
  ecsfs:
