version: "3"
services:
  postgres:
    image: 'postgres:latest'
    networks:
      ecsfs:
        aliases:
          - ecsfs-postgres.local
  redis:
    image: 'redis:latest'
    networks:
      ecsfs:
        aliases:
          - ecsfs-redis.local
  client:
    restart: always
    build: ./client
    networks:
      ecsfs:
        aliases:
          - ecsfs-frontend.local
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    restart: always
    build: ./server
    networks:
      ecsfs:
        aliases:
          - ecsfs-backend.local
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    command: npm run dev
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    networks:
      ecsfs:
    command: /bin/bash -c "envsubst  > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

networks:
  ecsfs:
